version: "3.7"
services:
  nginx:
    container_name: nginx-xyhcms
    build: ./nginx
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - ./source:/usr/share/nginx/html:rw
      - ./nginx/templates:/etc/nginx/templates
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8888:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=80
    restart: always
  php-fpm:
    container_name: php-fpm-xyhcms
    build:
      context: ./php-fpm
      args:
        - APP_CODE_PATH=${APP_CODE_PATH}
    environment:
      PHP_IDE_CONFIG: serverName=${NGINX_HOST}
    volumes:
      - ./source:/usr/share/nginx/html:rw
  mysql:
    container_name: mysql-xyhcms
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always